### ISSUE TITLE
Can't set spider priority in URL Filters

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#18] opened 2017-02-03 19:23 UTC
Can't set spider priority in URL Filters

**Comment by alc-privacore** [comment] 2017-02-07 10:30
Which url filter profile are you using?

**Comment by MikeLx** [comment] 2017-02-07 10:54
Custom

**Comment by br-privacore** [comment] 2017-02-24 10:16
Confirmed. Looks like a bug.

**Comment by ghost** [comment] 2017-02-24 13:30
Fixed in commit 51484abe432dd6fadd7610b915c1b391dc08022a

**Closed as completed by ghost** 2017-02-24 13:30 UTC
